In [1]:
%load_ext autoreload
%autoreload 2

# Test Metadata

In [2]:
import seaborn as sns
import duckdb

conn = duckdb.connect()
conn.register("tips", sns.load_dataset("tips"))
conn.execute("SELECT * FROM tips;").df()

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [3]:
from broinsight.utils.data_spec import Metadata, TableSpec, FieldSpec, create_field_specs_from_profile, FieldDescription, FieldDescriptions
from broinsight.data_quality.sql_profile import sql_field_profile, sql_table_profile

# Get profiles
tbl_prof = sql_table_profile(conn, "tips")
field_prof = sql_field_profile(conn, "tips")

# Create specs
table_spec = TableSpec(**tbl_prof)
field_specs = create_field_specs_from_profile(field_prof)

# Create metadata
metadata = Metadata(
    table_name="tips", # this must matches the table name of data
    table_description="Restaurant tips dataset", # this should be human-readable summary
    table_spec=table_spec, # mandatory
    field_spec=field_specs # mandatory
)

In [4]:
# field description here is important because it'll convert to LLM context later by DataCatalog and fetch it to BroInsight.method(...)

descriptions = dict(
    total_bill="the amount of paid bill of the meal",
    tip="the amount of tip that customers paid",
    sex="the gender of customers",
    smoker="it indicates that a customer is a smoker or not. if No means a customer is a non-smoker, Yes means a customer is a smoker.",
    day="this is a day of the week when a customer having a meal here. i.e. Mon, Tue, Wed, Thu, Fri, Sat, Sun",
    time="the time of the meal. it can be either Dinner or Lunch",
    size="the number of dishes that customers have",
)

field_descriptions = [
    FieldDescription(field_name=k, description=v) for k, v in descriptions.items()
]

metadata.add_field_descriptions(field_descriptions=FieldDescriptions(descriptions=field_descriptions))

In [5]:
from broinsight.utils.data_spec import create_data_quality_assessment

# Add quality assessment to metadata
quality_assessment = create_data_quality_assessment(field_prof)
metadata.add_data_quality_assessment(quality_assessment)

In [6]:
metadata

Metadata(table_name='tips', table_description='Restaurant tips dataset', table_spec=TableSpec(rows=244, columns=7, duplicates=1, evidences={0: {'total_bill': 13.0, 'tip': 2.0, 'sex': 'Female', 'smoker': 'Yes', 'day': 'Thur', 'time': 'Lunch', 'size': 2, 'dup_count': 2}}), field_spec=[FieldSpec(field_name='total_bill', data_type='float', missing_values=0, missing_values_pct=0.0, unique_values=229, unique_values_pct=0.94, most_frequent={13.42: 3, 18.29: 2, 10.07: 2, 20.29: 2, 10.34: 2}, statistics={'min': 3.07, 'max': 50.81, 'mean': 19.79, 'median': 17.8, 'std': 8.9, 'var': 79.25, 'skew': 1.13, 'kurt': 1.22, 'iqr': 10.78, 'cv': 0.45, 'lower_bound': -2.82, 'upper_bound': 40.3}, description='the amount of paid bill of the meal'), FieldSpec(field_name='tip', data_type='float', missing_values=0, missing_values_pct=0.0, unique_values=123, unique_values_pct=0.5, most_frequent={2.0: 33, 3.0: 23, 4.0: 12, 2.5: 10, 5.0: 10}, statistics={'min': 1.0, 'max': 10.0, 'mean': 3.0, 'median': 2.9, 'std': 1.38, 'var': 1.91, 'skew': 1.47, 'kurt': 3.65, 'iqr': 1.56, 'cv': 0.46, 'lower_bound': -0.34, 'upper_bound': 5.91}, description='the amount of tip that customers paid'), FieldSpec(field_name='sex', data_type='string', missing_values=0, missing_values_pct=0.0, unique_values=2, unique_values_pct=0.01, most_frequent={'Male': 157, 'Female': 87}, statistics={'mode': 'Male', 'avg_length': 4.71, 'min_length': 4, 'max_length': 6, 'empty_count': 0, 'whitespace_count': 0, 'pattern_consistency': 0.01}, description='the gender of customers'), FieldSpec(field_name='smoker', data_type='string', missing_values=0, missing_values_pct=0.0, unique_values=2, unique_values_pct=0.01, most_frequent={'No': 151, 'Yes': 93}, statistics={'mode': 'No', 'avg_length': 2.38, 'min_length': 2, 'max_length': 3, 'empty_count': 0, 'whitespace_count': 0, 'pattern_consistency': 0.01}, description='it indicates that a customer is a smoker or not. if No means a customer is a non-smoker, Yes means a customer is a smoker.'), FieldSpec(field_name='day', data_type='string', missing_values=0, missing_values_pct=0.0, unique_values=4, unique_values_pct=0.02, most_frequent={'Sat': 87, 'Sun': 76, 'Thur': 62, 'Fri': 19}, statistics={'mode': 'Sat', 'avg_length': 3.25, 'min_length': 3, 'max_length': 4, 'empty_count': 0, 'whitespace_count': 0, 'pattern_consistency': 0.02}, description='this is a day of the week when a customer having a meal here. i.e. Mon, Tue, Wed, Thu, Fri, Sat, Sun'), FieldSpec(field_name='time', data_type='string', missing_values=0, missing_values_pct=0.0, unique_values=2, unique_values_pct=0.01, most_frequent={'Dinner': 176, 'Lunch': 68}, statistics={'mode': 'Dinner', 'avg_length': 5.72, 'min_length': 5, 'max_length': 6, 'empty_count': 0, 'whitespace_count': 0, 'pattern_consistency': 0.01}, description='the time of the meal. it can be either Dinner or Lunch'), FieldSpec(field_name='size', data_type='integer', missing_values=0, missing_values_pct=0.0, unique_values=6, unique_values_pct=0.02, most_frequent={2: 156, 3: 38, 4: 37, 5: 5, 6: 4}, statistics={'min': 1, 'max': 6, 'mean': 2.57, 'median': 2.0, 'std': 0.95, 'var': 0.9, 'skew': 1.45, 'kurt': 1.73, 'iqr': 1.0, 'cv': 0.37, 'lower_bound': 0.5, 'upper_bound': 4.5}, description='the number of dishes that customers have')], field_descriptions=FieldDescriptions(descriptions=[FieldDescription(field_name='total_bill', description='the amount of paid bill of the meal'), FieldDescription(field_name='tip', description='the amount of tip that customers paid'), FieldDescription(field_name='sex', description='the gender of customers'), FieldDescription(field_name='smoker', description='it indicates that a customer is a smoker or not. if No means a customer is a non-smoker, Yes means a customer is a smoker.'), FieldDescription(field_name='day', description='this is a day of the week when a customer having a meal here. i.e. Mon, Tue, Wed, Thu, Fri, Sat, Sun'), FieldDescription(field_name='time', description='the time of the meal. it can be either Dinner or Lunch'), FieldDescription(field_name='size', description='the number of dishes that customers have')]), data_quality=DataQualityAssessment(field_assessments=[FieldQualityAssessment(field_name='total_bill', quality='good', issues=[QualityIssue(type='moderate_skewness', severity='minor', description='Moderately skewed distribution (skew: 1.13)')], issue_count=1), FieldQualityAssessment(field_name='tip', quality='good', issues=[QualityIssue(type='moderate_skewness', severity='minor', description='Moderately skewed distribution (skew: 1.47)')], issue_count=1), FieldQualityAssessment(field_name='sex', quality='good', issues=[], issue_count=0), FieldQualityAssessment(field_name='smoker', quality='good', issues=[], issue_count=0), FieldQualityAssessment(field_name='day', quality='good', issues=[], issue_count=0), FieldQualityAssessment(field_name='time', quality='good', issues=[], issue_count=0), FieldQualityAssessment(field_name='size', quality='good', issues=[QualityIssue(type='moderate_skewness', severity='minor', description='Moderately skewed distribution (skew: 1.45)')], issue_count=1)], overall_quality='good', total_issues=3))

In [7]:
metadata.__dict__.keys()

dict_keys(['table_name', 'table_description', 'table_spec', 'field_spec', 'field_descriptions', 'data_quality'])

In [8]:
metadata.table_name

'tips'

In [9]:
metadata.table_description

'Restaurant tips dataset'

In [10]:
metadata.table_spec.__dict__.keys()

dict_keys(['rows', 'columns', 'duplicates', 'evidences'])

In [11]:
metadata.field_spec

[FieldSpec(field_name='total_bill', data_type='float', missing_values=0, missing_values_pct=0.0, unique_values=229, unique_values_pct=0.94, most_frequent={13.42: 3, 18.29: 2, 10.07: 2, 20.29: 2, 10.34: 2}, statistics={'min': 3.07, 'max': 50.81, 'mean': 19.79, 'median': 17.8, 'std': 8.9, 'var': 79.25, 'skew': 1.13, 'kurt': 1.22, 'iqr': 10.78, 'cv': 0.45, 'lower_bound': -2.82, 'upper_bound': 40.3}, description='the amount of paid bill of the meal'),
 FieldSpec(field_name='tip', data_type='float', missing_values=0, missing_values_pct=0.0, unique_values=123, unique_values_pct=0.5, most_frequent={2.0: 33, 3.0: 23, 4.0: 12, 2.5: 10, 5.0: 10}, statistics={'min': 1.0, 'max': 10.0, 'mean': 3.0, 'median': 2.9, 'std': 1.38, 'var': 1.91, 'skew': 1.47, 'kurt': 3.65, 'iqr': 1.56, 'cv': 0.46, 'lower_bound': -0.34, 'upper_bound': 5.91}, description='the amount of tip that customers paid'),
 FieldSpec(field_name='sex', data_type='string', missing_values=0, missing_values_pct=0.0, unique_values=2, unique_values_pct=0.01, most_frequent={'Male': 157, 'Female': 87}, statistics={'mode': 'Male', 'avg_length': 4.71, 'min_length': 4, 'max_length': 6, 'empty_count': 0, 'whitespace_count': 0, 'pattern_consistency': 0.01}, description='the gender of customers'),
 FieldSpec(field_name='smoker', data_type='string', missing_values=0, missing_values_pct=0.0, unique_values=2, unique_values_pct=0.01, most_frequent={'No': 151, 'Yes': 93}, statistics={'mode': 'No', 'avg_length': 2.38, 'min_length': 2, 'max_length': 3, 'empty_count': 0, 'whitespace_count': 0, 'pattern_consistency': 0.01}, description='it indicates that a customer is a smoker or not. if No means a customer is a non-smoker, Yes means a customer is a smoker.'),
 FieldSpec(field_name='day', data_type='string', missing_values=0, missing_values_pct=0.0, unique_values=4, unique_values_pct=0.02, most_frequent={'Sat': 87, 'Sun': 76, 'Thur': 62, 'Fri': 19}, statistics={'mode': 'Sat', 'avg_length': 3.25, 'min_length': 3, 'max_length': 4, 'empty_count': 0, 'whitespace_count': 0, 'pattern_consistency': 0.02}, description='this is a day of the week when a customer having a meal here. i.e. Mon, Tue, Wed, Thu, Fri, Sat, Sun'),
 FieldSpec(field_name='time', data_type='string', missing_values=0, missing_values_pct=0.0, unique_values=2, unique_values_pct=0.01, most_frequent={'Dinner': 176, 'Lunch': 68}, statistics={'mode': 'Dinner', 'avg_length': 5.72, 'min_length': 5, 'max_length': 6, 'empty_count': 0, 'whitespace_count': 0, 'pattern_consistency': 0.01}, description='the time of the meal. it can be either Dinner or Lunch'),
 FieldSpec(field_name='size', data_type='integer', missing_values=0, missing_values_pct=0.0, unique_values=6, unique_values_pct=0.02, most_frequent={2: 156, 3: 38, 4: 37, 5: 5, 6: 4}, statistics={'min': 1, 'max': 6, 'mean': 2.57, 'median': 2.0, 'std': 0.95, 'var': 0.9, 'skew': 1.45, 'kurt': 1.73, 'iqr': 1.0, 'cv': 0.37, 'lower_bound': 0.5, 'upper_bound': 4.5}, description='the number of dishes that customers have')]

In [12]:
metadata.field_spec[0].__dict__.keys()

dict_keys(['field_name', 'data_type', 'missing_values', 'missing_values_pct', 'unique_values', 'unique_values_pct', 'most_frequent', 'statistics', 'description'])

# Test with AWS Bedrock

## One pandas table

In [13]:
from broinsight.experiment.bedrock import AWSConfig, BedrockOpenAI
from broinsight.experiment.ollama import LocalOpenAI
from broinsight.broinsight import BroInsight
import boto3

from broinsight.utils.data_catalog import DataCatalog
import seaborn as sns

field_descriptions = FieldDescriptions(descriptions=[
    FieldDescription(field_name="total_bill", description="Total bill amount in dollars"),
    FieldDescription(field_name="tip", description="Tip amount in dollars"),
    FieldDescription(field_name="sex", description="Customer gender"),
    FieldDescription(field_name="smoker", description="Whether customer smokes"),
    FieldDescription(field_name="day", description="Day of the week"),
    FieldDescription(field_name="time", description="Meal time (Lunch/Dinner)"),
    FieldDescription(field_name="size", description="Party size")
])

# Create catalog and register data
catalog = DataCatalog()
catalog.register("tips", sns.load_dataset("tips"), "Restaurant tips dataset")

# Profile the table
catalog.profile_tables(["tips"])

# Add field descriptions
catalog.add_field_descriptions("tips", field_descriptions)

session = boto3.Session()
credentials = session.get_credentials()

aws_configs = AWSConfig(
    aws_access_key_id=credentials.access_key,
    aws_secret_access_key=credentials.secret_key,
    aws_session_token=credentials.token or None,
    region_name='us-west-2'
)

model_id="openai.gpt-oss-20b-1:0"
bedrock = BedrockOpenAI(
    model_id=model_id,
    aws_configs=aws_configs
)

# broinsight = BroInsight(model=LocalOpenAI())
broinsight = BroInsight(model=bedrock)

In [14]:
# check data quality
response = broinsight.assess_data_quality(
    context=catalog.to_dq_profile("tips"),
    message="Do we have any concern about this one?"
)
print(response['content'])

**Data Quality Assessment: READY**

**Critical Issues Found:** None – the dataset has no missing values, duplicates are minimal, and all columns are well‑defined.

**Recommended Actions (Optional):**
- **Skewed numeric fields** (`total_bill`, `tip`, `size`) have moderate right‑skewness (skew ≈ 1.1–1.5).
  - If you plan to use parametric models that assume normality (e.g., linear regression, ANOVA), consider applying a log or square‑root transformation to these variables.
  - For non‑parametric or tree‑based methods (e.g., random forests, gradient boosting), the skewness is less of a concern.
- **Exploratory checks**: Plot histograms or boxplots to confirm the skewness and identify any outliers that might influence model performance.

**Next Steps:**
- Proceed with your analysis.
- If you encounter model diagnostics indicating non‑normal residuals or heteroscedasticity, revisit the transformations above.

**Overall Recommendation:** The dataset is ready for analysis; the only caveat is the moderate skewness in a few numeric fields, which can be addressed with simple transformations if needed.

In [15]:
# ask for suggestions based on specific data in data catalog
response = broinsight.suggest_questions(
    context=catalog.to_guide_metadata("tips"),
    message="I'm a new manager and I wanna make a promotion for the shop but I don't know how to start."
)
print(response['content'])

Based on your role and goals, here are some areas you might want to explore:

Customer Demographics & Behavior
- What is the average tip amount for Male versus Female customers? (sex, tip)
- How does the average tip differ between Smokers and Non‑Smokers? (smoker, tip)

Dining Timing & Patterns
- Which day of the week has the highest average total bill? (day, total_bill)
- What is the average party size for Lunch compared to Dinner? (time, size)

Spending & Tip Trends
- What is the average tip percentage (tip ÷ total_bill) for each day of the week? (day, tip, total_bill)
- Which meal time (Lunch or Dinner) has the highest average tip amount? (time, tip)

Party Size Impact
- How does the average total bill change with party size? (size, total_bill)
- What is the average tip amount for parties of size 4 or more? (size, tip)

Just ask me any of these questions and I'll analyze your data to get the answers!

In [16]:
# create sql query from selected table
question = "What is the average total_bill for size = 1 compared to size = 4 or more?"
response = broinsight.generate_sql(
    context=catalog.to_sql_metadata("tips"),
    message=question
)
print(response['content'])

```sql
SELECT
    CASE
        WHEN size = 1 THEN 'size = 1'
        ELSE 'size >= 4'
    END AS size_category,
    AVG(total_bill) AS avg_total_bill
FROM tips
WHERE size = 1 OR size >= 4
GROUP BY size_category
ORDER BY size_category;
```

In [17]:
# parsing sql query and get result
sql_query = response['content'].split("```sql")[-1].split("```")[0]
result = catalog.query(sql_query)
result

  size_category  avg_total_bill
0      size = 1        7.242500
1     size >= 4       29.312174

In [18]:
# ask data is just asking data that we get from sql query and put it as a context
response = broinsight.ask_data(
    context=result.to_string(),
    message=question
)
print(response['content'])

The data shows that when a party is just one person, the average total bill is **$7.24**. For parties of four or more, the average climbs to **$29.31**.

**What this means for your business**

- **Higher spend per larger group**: A group of four or more spends roughly four times as much as a single diner. That’s a strong incentive to encourage larger parties—perhaps through group‑friendly menus, table‑sharing promotions, or special group pricing.
- **Targeted upselling**: Since larger groups already spend more, you could focus upsell efforts (e.g., appetizers, desserts, drinks) on those tables to boost revenue further.
- **Capacity planning**: Knowing that larger parties generate significantly higher revenue can help you optimize seating and staffing during peak times.

**Next steps**

1. **Explore the drivers**: Are the higher bills due to more items, higher‑priced menu choices, or drinks? Look at item‑level data for size ≥ 4 groups.
2. **Promote group dining**: Consider marketing campaigns or loyalty perks that specifically target groups of four or more.
3. **Monitor trends**: Track whether this gap widens or narrows over time—especially if you introduce new menu items or pricing changes.

Let me know if you’d like to dig deeper into the menu items or time‑of‑day patterns for these groups!

In [19]:
# it's almost the same flow as above but it will return a chart, instead of text
response = broinsight.create_chart(
    query_result=result,
    message=question
)
response['chart']
# print(response['fig'])

## Two s3 tables

Down below is almost the above example except it takes more than one table to do the job

In [20]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Dataset 1: Customers
np.random.seed(42)
customers_data = {
    'customer_id': range(1, 101),
    'name': [f'Customer_{i}' for i in range(1, 101)],
    'email': [f'customer{i}@email.com' for i in range(1, 101)],
    'age': np.random.randint(18, 75, 100),
    'city': np.random.choice(['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'], 100),
    'signup_date': [datetime(2023, 1, 1) + timedelta(days=np.random.randint(0, 365)) for _ in range(100)],
    'status': np.random.choice(['Active', 'Inactive'], 100, p=[0.8, 0.2])
}
customers_df = pd.DataFrame(customers_data)

# Dataset 2: Orders (with foreign key to customers)
np.random.seed(42)
orders_data = {
    'order_id': range(1, 251),
    'customer_id': np.random.choice(range(1, 101), 250),  # Foreign key to customers
    'order_date': [datetime(2023, 1, 1) + timedelta(days=np.random.randint(0, 365)) for _ in range(250)],
    'product_category': np.random.choice(['Electronics', 'Clothing', 'Books', 'Home', 'Sports'], 250),
    'order_amount': np.round(np.random.uniform(10.0, 500.0, 250), 2),
    'shipping_cost': np.round(np.random.uniform(0.0, 25.0, 250), 2),
    'order_status': np.random.choice(['Completed', 'Pending', 'Cancelled'], 250, p=[0.7, 0.2, 0.1]),
    'payment_method': np.random.choice(['Credit Card', 'PayPal', 'Bank Transfer'], 250)
}
orders_df = pd.DataFrame(orders_data)

# Field descriptions for customers
customers_descriptions = FieldDescriptions(descriptions=[
    FieldDescription(field_name="customer_id", description="Unique customer identifier"),
    FieldDescription(field_name="name", description="Customer full name"),
    FieldDescription(field_name="email", description="Customer email address"),
    FieldDescription(field_name="age", description="Customer age in years"),
    FieldDescription(field_name="city", description="Customer's city of residence"),
    FieldDescription(field_name="signup_date", description="Date when customer registered"),
    FieldDescription(field_name="status", description="Current customer account status")
])

# Field descriptions for orders
orders_descriptions = FieldDescriptions(descriptions=[
    FieldDescription(field_name="order_id", description="Unique order identifier"),
    FieldDescription(field_name="customer_id", description="Links to customer who placed the order"),
    FieldDescription(field_name="order_date", description="Date when order was placed"),
    FieldDescription(field_name="product_category", description="Category of products ordered"),
    FieldDescription(field_name="order_amount", description="Total order value in dollars"),
    FieldDescription(field_name="shipping_cost", description="Shipping fee charged"),
    FieldDescription(field_name="order_status", description="Current status of the order"),
    FieldDescription(field_name="payment_method", description="Payment method used")
])

In [21]:
from broinsight.utils.data_catalog import DataCatalog
import boto3

s3_client = boto3.client('s3')
bucket='dev-broinsight'

aws_configs = AWSConfig(
    aws_access_key_id=credentials.access_key,
    aws_secret_access_key=credentials.secret_key,
    aws_session_token=credentials.token or None,
    region_name='ap-southeast-1'
)

s3_client.put_object(Bucket=bucket, Key='customers.csv', Body=customers_df.to_csv(index=False))
s3_client.put_object(Bucket=bucket, Key='orders.csv', Body=orders_df.to_csv(index=False))

s3_customers = f"s3://{bucket}/customers.csv"
s3_orders = f"s3://{bucket}/orders.csv"

catalog = DataCatalog(aws_configs=aws_configs)
# catalog.register("customers", customers_df, "Customer information and demographics")
# catalog.register("orders", orders_df, "Customer order transactions and details")

catalog.register("customers", s3_customers, "Customer information and demographics")
catalog.register("orders", s3_orders, "Customer order transactions and details")
# # Profile tables
catalog.profile_tables(["customers", "orders"])

# # Add field descriptions
catalog.add_field_descriptions("customers", customers_descriptions)
catalog.add_field_descriptions("orders", orders_descriptions)

# # Add relationship
# catalog.add_relationship("orders", "customer_id", "customers", "customer_id")
catalog.add_relationship(foreign_table="orders", foreign_key="customer_id", primary_table="customers", primary_key="customer_id")

# # Test SQL metadata generation
sql_metadata = catalog.to_sql_metadata(["customers", "orders"])
print(sql_metadata)

METADATAS:

Table: customers
Columns:
- customer_id (integer): Unique customer identifier, NOT NULL
  Range: 1 - 100, Average: 50.50
- name (string): Customer full name, NOT NULL
  Examples: "Customer_10", "Customer_23", "Customer_30"
- email (string): Customer email address, NOT NULL
  Examples: "customer65@email.com", "customer69@email.com", "customer73@email.com"
- age (integer): Customer age in years, NOT NULL
  Range: 19 - 74, Average: 45.19
- city (string): Customer's city of residence, NOT NULL
  Examples: "New York", "Houston", "Chicago"
- signup_date (datetime): Date when customer registered, NOT NULL
  Range: 2023-01-02 00:00:00 to 2023-12-26 00:00:00, 77 unique days
- status (string): Current customer account status, NOT NULL
  Examples: "Active", "Inactive"

Table: orders
Relationships:
  customer_id -> customers.customer_id
Columns:
- order_id (integer): Unique order identifier, NOT NULL
  Range: 1 - 250, Average: 125.50
- customer_id (integer): Links to customer who placed the order, NOT NULL
  Range: 1 - 100, Average: 50.34
- order_date (datetime): Date when order was placed, NOT NULL
  Range: 2023-01-01 00:00:00 to 2023-12-31 00:00:00, 176 unique days
- product_category (string): Category of products ordered, NOT NULL
  Examples: "Sports", "Home", "Electronics"
- order_amount (float): Total order value in dollars, NOT NULL
  Range: 11.27 - 498.87, Average: 260.16
- shipping_cost (float): Shipping fee charged, NOT NULL
  Range: 0.06 - 24.98, Average: 12.95
- order_status (string): Current status of the order, NOT NULL
  Examples: "Completed", "Pending", "Cancelled"
- payment_method (string): Payment method used, NOT NULL
  Examples: "PayPal", "Credit Card", "Bank Transfer"

In [22]:
response = broinsight.suggest_questions(
    context=catalog.to_guide_metadata(["customers", "orders"]),
    message="I'm a new manager here. I don't know what to look to know more about our business."

)
print(response['content'])

Based on your role and goals, here are some areas you might want to explore:

Customer Overview
- How many customers are Active versus Inactive in the customers table?
- What is the average age of customers in each city?
- How many customers signed up each month based on signup_date?

Order Performance
- What is the total and average order_amount per month in the orders table?
- How many orders are Completed, Pending, or Cancelled?
- What is the average shipping_cost per order?

Product Category Insights
- Which product_category has the highest total order_amount?
- What is the average order_amount for each product_category?
- How many orders are placed in each product_category?

Customer Acquisition & Retention
- How many new customers signed up each month?
- How many of those new customers placed at least one order?
- What is the average order_amount for the first order of each new customer?

Just ask me any of these questions and I'll analyze your data to get the answers!

In [23]:
# question = "How many orders were paid using each payment_method in the orders table?"
# question = "Who are the top 5 customers payting with PayPal method? I wanna know thier ages and names"
# question = "Who are the top 5 spenders? I wanna know thier ages and names and their most payment method"
question = "Show me monthly sales trends of each year"
response = broinsight.generate_sql(
    context=catalog.to_sql_metadata(["customers", "orders"]),
    message=question

)
print(response['content'])

```sql
SELECT
    EXTRACT(YEAR FROM order_date)  AS sales_year,
    EXTRACT(MONTH FROM order_date) AS sales_month,
    SUM(order_amount)              AS total_sales
FROM orders
WHERE order_status = 'Completed'
GROUP BY sales_year, sales_month
ORDER BY sales_year, sales_month;
```

In [24]:
sql_query = response['content'].split("```sql")[-1].split("```")[0]
result = catalog.query(sql_query)

In [25]:
result

    sales_year  sales_month  total_sales
0         2023            1      2427.12
1         2023            2      3037.51
2         2023            3      1549.73
3         2023            4      3798.10
4         2023            5      5520.59
5         2023            6      5578.09
6         2023            7      2987.18
7         2023            8      2729.77
8         2023            9      4984.97
9         2023           10      3243.12
10        2023           11      3134.15
11        2023           12      3930.74

In [26]:
response = broinsight.ask_data(
    context=result.to_string(),
    message=question
)
print(response['content'])

I only have the 2023 monthly figures in the data you shared, so I’ll walk through that year’s trend for you.

**2023 Monthly Sales Snapshot**

| Month | Total Sales |
|-------|-------------|
| Jan   | $2,427.12   |
| Feb   | $3,037.51   |
| Mar   | $1,549.73   |
| Apr   | $3,798.10   |
| May   | $5,520.59   |
| Jun   | $5,578.09   |
| Jul   | $2,987.18   |
| Aug   | $2,729.77   |
| Sep   | $4,984.97   |
| Oct   | $3,243.12   |
| Nov   | $3,134.15   |
| Dec   | $3,930.74   |

**What the numbers tell us**

- **Peak Season:** The highest sales came in **May ($5,520.59)** and **June ($5,578.09)**, suggesting a strong mid‑year push—perhaps a product launch, seasonal promotion, or a holiday‑related spike.
- **Lowest Point:** **March ($1,549.73)** was the lowest month, which could indicate a post‑holiday dip or a period of lower demand.
- **Mid‑Year Dip:** After the June peak, sales drop to around $3,000 in July and August, then climb again in September ($4,984.97). This pattern might reflect a summer slowdown followed by a rebound as the back‑to‑school or early‑fall season kicks in.
- **Consistent Winter Performance:** December ($3,930.74) is higher than the average of the last quarter, hinting at a modest holiday boost.

**Next steps**

1. **Compare with Prior Years:** If you have 2022 or earlier data, overlay those months to see if the May‑June peak is a new trend or a recurring pattern.
2. **Investigate Drivers:** Look at marketing campaigns, product launches, or external events that align with the spikes in May, June, and September.
3. **Plan for the Low Periods:** For March and the summer months, consider targeted promotions or inventory adjustments to smooth out the dip.
4. **Seasonal Forecasting:** Use this trend as a baseline for forecasting next year’s monthly sales, adjusting for any known changes in your business environment.

Let me know if you’d like to dive deeper into any specific month or compare these figures with another year’s data!

In [27]:
response = broinsight.create_chart(
    query_result=result,
    message=question
)
response['chart']

In [28]:
catalog.list_tables()

['customers', 'orders']

In [29]:
catalog.query("SELECT * FROM customers LIMIT 5")

,customer_id,name,email,age,city,signup_date,status
0,1,Customer_1,customer1@email.com,56,Phoenix,2023-09-25,Active
1,2,Customer_2,customer2@email.com,69,Los Angeles,2023-10-22,Active
2,3,Customer_3,customer3@email.com,46,New York,2023-04-23,Active
3,4,Customer_4,customer4@email.com,32,Houston,2023-04-11,Active
4,5,Customer_5,customer5@email.com,60,Houston,2023-04-23,Active

In [30]:
catalog.query("SELECT * FROM customers LIMIT 5").info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  5 non-null      int64
 1   name         5 non-null      object
 2   email        5 non-null      object
 3   age          5 non-null      int64
 4   city         5 non-null      object
 5   signup_date  5 non-null      datetime64[us]
 6   status       5 non-null      object
dtypes: datetime64[us](1), int64(2), object(4)
memory usage: 412.0+ bytes

In [31]:
print(catalog.to_dq_profile("customers"))

DATASET: customers
DESCRIPTION: Customer information and demographics
ROWS: 100
COLUMNS: 7
DUPLICATES: 0
OVERALL QUALITY: GOOD
TOTAL ISSUES: 0

FIELD PROFILES:

customer_id (integer):
  Missing: 0 (0.0%)
  Unique: 100 (1.0%)
  Description: Unique customer identifier

name (string):
  Missing: 0 (0.0%)
  Unique: 100 (1.0%)
  Description: Customer full name

email (string):
  Missing: 0 (0.0%)
  Unique: 100 (1.0%)
  Description: Customer email address

age (integer):
  Missing: 0 (0.0%)
  Unique: 50 (0.5%)
  Description: Customer age in years

city (string):
  Missing: 0 (0.0%)
  Unique: 5 (0.1%)
  Description: Customer's city of residence

signup_date (datetime):
  Missing: 0 (0.0%)
  Unique: 77 (0.8%)
  Description: Date when customer registered

status (string):
  Missing: 0 (0.0%)
  Unique: 2 (0.0%)
  Description: Current customer account status

In [32]:
print(catalog.to_guide_metadata("customers"))

METADATA:

Table: customers (Customer information and demographics)
Fields:
- customer_id (integer): Unique customer identifier
  Range: 1 - 100, Average: 50.50
- name (string): Customer full name
  Values: Customer_10 (1), Customer_23 (1), Customer_30 (1)
- email (string): Customer email address
  Values: customer65@email.com (1), customer69@email.com (1), customer73@email.com (1)
- age (integer): Customer age in years
  Range: 19 - 74, Average: 45.19
- city (string): Customer's city of residence
  Values: New York (27), Houston (22), Chicago (21)
- signup_date (datetime): Date when customer registered
  Range: 2023-01-02 00:00:00 to 2023-12-26 00:00:00, 77 unique days
- status (string): Current customer account status
  Values: Active (82), Inactive (18)

In [33]:
print(catalog.to_guide_metadata(table_names=["customers", "orders"]))

METADATA:

Table: customers (Customer information and demographics)
Fields:
- customer_id (integer): Unique customer identifier
  Range: 1 - 100, Average: 50.50
- name (string): Customer full name
  Values: Customer_10 (1), Customer_23 (1), Customer_30 (1)
- email (string): Customer email address
  Values: customer65@email.com (1), customer69@email.com (1), customer73@email.com (1)
- age (integer): Customer age in years
  Range: 19 - 74, Average: 45.19
- city (string): Customer's city of residence
  Values: New York (27), Houston (22), Chicago (21)
- signup_date (datetime): Date when customer registered
  Range: 2023-01-02 00:00:00 to 2023-12-26 00:00:00, 77 unique days
- status (string): Current customer account status
  Values: Active (82), Inactive (18)

Table: orders (Customer order transactions and details)
Fields:
- order_id (integer): Unique order identifier
  Range: 1 - 250, Average: 125.50
- customer_id (integer): Links to customer who placed the order
  Range: 1 - 100, Average: 50.34
- order_date (datetime): Date when order was placed
  Range: 2023-01-01 00:00:00 to 2023-12-31 00:00:00, 176 unique days
- product_category (string): Category of products ordered
  Values: Sports (59), Home (51), Electronics (50)
- order_amount (float): Total order value in dollars
  Range: 11.27 - 498.87, Average: 260.16
- shipping_cost (float): Shipping fee charged
  Range: 0.06 - 24.98, Average: 12.95
- order_status (string): Current status of the order
  Values: Completed (166), Pending (56), Cancelled (28)
- payment_method (string): Payment method used
  Values: PayPal (91), Credit Card (81), Bank Transfer (78)

In [34]:
print(catalog.to_sql_metadata(table_names=["customers", "orders"]))

METADATAS:

Table: customers
Columns:
- customer_id (integer): Unique customer identifier, NOT NULL
  Range: 1 - 100, Average: 50.50
- name (string): Customer full name, NOT NULL
  Examples: "Customer_10", "Customer_23", "Customer_30"
- email (string): Customer email address, NOT NULL
  Examples: "customer65@email.com", "customer69@email.com", "customer73@email.com"
- age (integer): Customer age in years, NOT NULL
  Range: 19 - 74, Average: 45.19
- city (string): Customer's city of residence, NOT NULL
  Examples: "New York", "Houston", "Chicago"
- signup_date (datetime): Date when customer registered, NOT NULL
  Range: 2023-01-02 00:00:00 to 2023-12-26 00:00:00, 77 unique days
- status (string): Current customer account status, NOT NULL
  Examples: "Active", "Inactive"

Table: orders
Relationships:
  customer_id -> customers.customer_id
Columns:
- order_id (integer): Unique order identifier, NOT NULL
  Range: 1 - 250, Average: 125.50
- customer_id (integer): Links to customer who placed the order, NOT NULL
  Range: 1 - 100, Average: 50.34
- order_date (datetime): Date when order was placed, NOT NULL
  Range: 2023-01-01 00:00:00 to 2023-12-31 00:00:00, 176 unique days
- product_category (string): Category of products ordered, NOT NULL
  Examples: "Sports", "Home", "Electronics"
- order_amount (float): Total order value in dollars, NOT NULL
  Range: 11.27 - 498.87, Average: 260.16
- shipping_cost (float): Shipping fee charged, NOT NULL
  Range: 0.06 - 24.98, Average: 12.95
- order_status (string): Current status of the order, NOT NULL
  Examples: "Completed", "Pending", "Cancelled"
- payment_method (string): Payment method used, NOT NULL
  Examples: "PayPal", "Credit Card", "Bank Transfer"